image: node:latest

cache:
  key: dependencies
  paths:
    - node_modules/

backend:
  script:
    - echo "DEBUGGING"
    # - cd ./backend
    # - npm install --prefer-offline --no-audit
    # - npm run test
