default:
  image: node:latest
  before_script:
    - npm install --prefer-offline --no-audit --progress=false

stages:
  - testing-backend

test:
  stage: testing-backend
  script:
    - npm run backend
